# Generated by Django 3.2.12 on 2022-03-02 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=django.utils.timezone.now)),
                ('oximeter', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('temp', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
