# Generated by Django 3.2.12 on 2022-03-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_sensor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
