# Generated by Django 3.2.12 on 2022-03-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_sensor_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=254)),
                ('pin_code', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('medical_history', models.CharField(max_length=254)),
                ('medical_problems', models.CharField(max_length=254)),
                ('allergies', models.CharField(max_length=254)),
            ],
        ),
    ]
