# Generated by Django 3.2.12 on 2022-03-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_care_taker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.IntegerField()),
                ('designation', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_address', models.CharField(max_length=254)),
            ],
        ),
    ]
