# Generated by Django 3.2.12 on 2022-04-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='oximeter',
            new_name='bpm',
        ),
        migrations.AddField(
            model_name='sensor',
            name='spo2',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
    ]
