# Generated by Django 3.2.12 on 2022-04-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20220418_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=254)),
                ('days', models.CharField(max_length=254)),
                ('time', models.TimeField()),
            ],
        ),
    ]
