# Generated by Django 3.2.12 on 2022-06-04 07:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='record',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
